apiVersion: v1
kind: Secret
metadata:
  name: supabase-secrets
type: Opaque
data:
  SUPABASE_URL: aHR0cHM6Ly91eHBzZ3RkaWx1bnVyaHFhYXNpaC5zdXBhYmFzZS5jbw== 
  SUPABASE_ANON_KEY: ZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SnBjM01pT2lKemRYQmhZbUZ6WlNJc0luSmxaaUk2SW5WNGNITm5kR1JwYkhWdWRYSm9jV0ZoYzJsb0lpd2ljbTlzWlNJNkltRnViMjRpTENKcFlYUWlPakUzTWpjM05EUTBNRFFzSW1WNGNDSTZNakEwTXpNeU1EUXdOSDAuN1pOelQ1emNBdlJ1ZzhyV001RE1zOU16QmVNZ3Y1aWZ2Ulp6ajllS3lEVQ==