FROM node:16

WORKDIR /app

# Copiar solo los archivos package*.json
COPY package*.json ./

# Instalar dependencias de producción
RUN npm install --production

# Copiar el resto del código
COPY . .

# Exponer el puerto 5001
EXPOSE 5004

# Comando para iniciar la aplicación
CMD ["npm", "start"]