apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 1  # Número de réplicas del pod
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: user-service-image
        ports:
        - containerPort: 5002
        env:
        - name: SUPABASE_URL
          valueFrom:
            secretKeyRef:
              name: supabase-secrets
              key: SUPABASE_URL
        - name: SUPABASE_ANON_KEY
          valueFrom:
            secretKeyRef:
              name: supabase-secrets
              key: SUPABASE_ANON_KEY
        - name: JWT_SECRET  
          valueFrom:
            secretKeyRef:
              name: auth-service-secrets 
              key: JWT_SECRET